### ISSUE TITLE
Nightly builds removed NoneError

### ISSUE THREAD

**Issue by sempervictus** [wokket/rust-hl7#2]
As of https://github.com/rust-lang/rust/pull/85482, Rust nightly does not include the original try_trait bit including NoneError. Is there any chance you might have time to convert the implementation to current try_trait v2 mechanisms or possibly even stable builds? Thanks

**Comment by wokket** [comment]
I'll have a look when I get a chance, but this was never really a serious library.  Is this request because you were hoping to use the library, or just trying to tidy up the ecosystem?

Ta

**Comment by sempervictus** [comment]
Looking at the two libs available, choice is between lots of tedious and static `Impl`s for the structs defined in the "other lib" or working out some sort of typing translation for your approach to produce differentiated structs (i come from Ruby and C so have a penchant for the dynamic stuff with a good comprehension of what happens lower-down, and being a glutton for punishment am trying to learn to do the dynamic bits better in Rust).
Neither lib seems quite production-grade, but HL7 data flows are growing every day, and the bloody format seems to have no intention of dying. There are enough absurd implementations in various languages out there to result in hospitals burning literally tons of money looking at them, and often-enough making their own for their specific extraction needs. Bringing either Rust lib to the point of being consistent and robust in data types seems like "the right thing to do" (at least so that when i end up in a hospital bed they're not confusing my telemetry for someone else').

**Comment by wokket** [comment]
Gotcha, spoken like someone who's spent plenty of time in healthcare ;)

I'll try and have a look tonight, but fair warning I was building this to help learn the language too 👍

**Comment by sempervictus** [comment]
Too much and not enough - i'm a security architect, pretty sure i've lost the ability to _have_ nightmares from desensitization.
Thanks for any progress you could make toward something buildable, the more i look at my current use case, the more it looks like i actually need a dynamic structure vs the static ones defined elsewhere. I have a naive reader mostly working, but its only for the fields i need and full-message only since MSH has separators between and inside other fields.

**Comment by wokket** [comment]
I've just published 0.2.1 to crates mate, let me know how it goes for you 👍

**Comment by sempervictus** [comment]
Thank you! Will start grokking shortly.
