### ISSUE TITLE
code simplification

### ISSUE THREAD

**Issue by yatesco** [wokket/rust-hl7#45]
(just a minor nit ;-):
https://github.com/wokket/rust-hl7/blob/e1b8456a76f316205a2c817827ecc8c0a412f36f/src/message.rs#L214 can be reduced to `let segments: Result<Vec<Segment>, E> = possible.into_iter().collect()?;`

:-)

**Comment by wokket** [comment]
Love it!  Given I don't even have rust installed at the moment, I'm very open to a small PR :)

Are you using this library for anything interesting?

**Comment by yatesco** [comment]
I'm not actually using it as we wrote our own parser using nom. I was idly musing how to query into the message and thought I'd search for prior art, and noticed your `TODO` :-)
